### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by nikeee**
All existing contributors must consent to this change.

Just reply with `:+1:` and we can merge this.
- @flxai
- @jplatte
- @anuejn
- @malled2002

### CODE REVIEW

**Comment by cfstras** [comment]
Why AGPL if https://github.com/flipdot/drinks-storage-order has 0BSD?

Also, how does AGPL even apply do schematics?

**Comment by nikeee** [comment]
I though (A)GPL would be a nice fit because it makes our work free software.

@cfstras
> Also, how does AGPL even apply do schematics?

Are there any in this repository? I only see SCAD files, which are hand-written.

**Comment by jplatte** [comment]
:+1:

**Comment by flxai** [comment]
> Why AGPL if https://github.com/flipdot/drinks-storage-order has 0BSD?

I'd prefer for all `drinks-storage-*` projects to use 0BSD if any license.

**Comment by nikeee** [comment]
Having no license would require us to ask every contributor for consent to use/modify the code, which is currently the case.

_We'd promote non-free software_ if we wouldn't choose a free software license. I don't see any reason we shouldn't license this as free software. That's why I propose AGPL or (a similar free software license) for our projects.

**Comment by flxai** [comment]
Good point!

**Pull request merged**
